PolymerElements/iron-input

- iron-input.html
- test/iron-input.html
If `preventInvalidInput=false`, `value` and `bindValue` weren't set correctly and no change notifications were sent out. I changed this to basically assume that the input is always valid if `preventInvalidInput=false`.
Also added a test and a small change in `_bindValueChanged` to make sure we don't validate twice (`onInput` calls `_validateValue` which calls `_bindValueChanged`, which really doesn't need to all `validateValue` again)
> Fix validation logic

- iron-input.html
This fixes https://github.com/PolymerElements/iron-input/issues/12
We can't decide whether a particular `iron-input` supports selection in its `ready` method since the type isn't set at that time (it's stamped later by the `PaperInputBehavior`)
I did this for all the invalid types, but if we only support text/number/password (as we advertise in `PaperInputBehavior`) then I can change it to a "type != number` check instead.
> not all input types support selection

- demo/index.html
- iron-input.html
- test/iron-input.html
@notwaldorf PTAL cc @cdata 
Previously it's difficult to use prevent-invalid-input and
validation together, because often you want to validate the
complete value but want to prevent invalid input while the
value is incomplete. This commit adds a `allowed-pattern`
attribute that lets you define a different pattern to match
new input with.
Support for prevent setting invalid input programmatically
is dropped. Setting value manually when it's invalid is
too error-prone.
> make prevent-invalid-input independent of validation

- bower.json
- iron-input.html
Fixes https://github.com/PolymerElements/paper-input/issues/36 and https://github.com/PolymerElements/iron-input/issues/19
`IronFormElementBehavior` also defines a `value` property, which stomps over the input's native `value`property, causing a rift in the space-time continuum. :(
Instead, `IronFormElementBehavior` needs to be added to `paper-input` and any `iron-input` containing brethren.
> remove IronFormElementBehavior which breaks everything

- iron-input.html
Empty, non-required strings are valid.
> empty values are sometimes valid

- iron-input.html
Added _correctNumpadKeys method to convert numpad keys 97 - 112 to number keys 47 - 58. String.fromCharCode returns lower case letters a - p for numpad keys 97 - 112 making allowed-pattern="[0-9]" impossible to add via the numpad.
> Convert printable numpad keys to number keys

- demo/index.html
- iron-input.html
- test/iron-input.html
Fixes https://github.com/PolymerElements/gold-cc-input/issues/18, https://github.com/PolymerElements/gold-cc-input/issues/19
To make the `shiftKey` work correctly, I changed `keydown` to `keypress`. This makes all the characters be translated correctly (and now the numpad keys work by magic as well).
To make pasting work correctly, we have to check the entire input value (which we haven't checked on `_keyPress`). I don't know how I can make that better :(
> ignore special keys when validating input

- iron-input.html
The Enter key cannot be used to commit input fields, because input validation
considers Enter non-printable and cancels the keypress event. After the change
you can use Enter to commit an input field (which fires a change event).
> Classify Enter as a non-printable character.

- iron-input.html
Fixes https://github.com/Polymer/paper-input/issues/184 and the surprise bug of not being able to tab out of gold elements.
@cdata @morethanreal
> allowing tabbing out of inputs

- iron-input.html
The compiler thinks that `this.bindValue` must be a string, so comparing it to 0 will always be false, which is suspicious.
I tried telling it that `this.bindValue` could be either a string or a number, but then it was unhappy because `this.value` should only be a string, and `this.value` comes in from `<input>` here.
> Quick fix: suppress checking types

- bower.json
- demo/index.html
- test/iron-input.html
Fixes the generic usage of `paper-styles.html` and `/deep/` classes and uses the specific imports instead. Also updates the test to the new `wct#^3.4.0` way
> stop bringing in the paper-styles kitchen sink

- iron-input.html
- test/iron-input.html
Currently, setting `bindValue` to `false` will set the input value to empty.
> Support boolean false as bindValue.

- iron-input.html
edit from @notwaldorf: From https://github.com/PolymerElements/paper-input/pull/296. Allows you to listen to the `invalid` event from the nested `<input>`, which is only triggered if `checkValidity` is called. Also, this makes sense since `paper-input-container`'s `_handleValueAndAutoValidate()` also calls `checkValidity`, so there's no real reason why this shouldn't also.
> call checkValidity() rather than checking .valid

- iron-input.html
- test/disabled-input.html
- test/iron-input.html
Fixes #47.
(this was originally opened in https://github.com/PolymerElements/iron-input/pull/48 a long time ago, but I picked it up here to finally merge it).
Original description
Firefox has a bug where calling dispatchEvent on a non-attached and disabled input throws.
This can happen when any notify: true value is set on a disabled input type extension before attached, which can happen via a binding, during configuration of a default value, or by setting a property in ready when it is in the local-DOM of another element (since it won't be attached until after ready).
Additionally, in debugging this, we also found out that Firefox will not actually dispatch events from disabled form controls (regardless of attachment), and IE will not actually dispatch events from ANY disabled element. …
> Patch dispatchEvent on FF & IE to avoid disabled bugs. Fixes #47

- iron-input.html
Clarify in the docs how `preventInvalidInput` and `allowedPattern` work in the docs. Closes issue #77.
(Should be a cleaner PR than #78 and also pass the clabot)
cc @notwaldorf for review
> update preventInvalidInput and allowedPattern docs

- bower.json
- iron-input.html
- test/index.html
- test/iron-input.html
Fixes https://github.com/PolymerElements/iron-input/issues/57.
We announce two messages:
- "Invalid character x not entered" whenever you're typing
- "Invalid string of characters not entered" whenever you paste something or manually call `_onInput`. The reason why this is different is that figuring out what the characters entered were is actually a bit expensive: you only have the string before you called `_onInput` , and the one after, and you would have to manually diff them which isn't trivial (if you paste in the middle of the string, you have to manually go through each character and figure out where the differences are). I'm not sure this is worth it, especially since reading that afterward is weird and potentially super verbose ("oops i accidentally pasted this entire tweet, …
> announce when invalid characters are blocked

- iron-input.html
polylint fails with the following error:
Property _inputElement not found in 'properties' for element 'iron-input'
This change explicitly adds the _inputElement property.
> Fix polylint failure

- iron-input.html
Closure Compiler with its Polymer pass is unhappy not knowing what type the computed value here is.
> add type to computed var for Closure

- iron-input.html
This was leftover code from when `iron-input` was a type extension and had a `type` attribute that was never updated correctly.
Among other things, fixes https://github.com/PolymerElements/iron-input/issues/121
/cc @aomarks
> Use the native input's type, not an inexistent property

- iron-input.html
`iron-input` 1.x had a default value of `""` (because the native `input` boots up with that value), but `iron-input` 2.x boots up with `undefined`.
> Set a default value

- .travis.yml
- demo/cats-only.html
- iron-input.d.ts
- iron-input.html
- package-lock.json
- package.json
- test/disabled-input.html
- test/iron-input.html
- test/letters-only.html
Runs the experimental autoformatter [webmat](https://github.com/PolymerLabs/webmat) which runs clang-format on js files and makes it so that it can run on HTML files. Please look through this PR with `?w=1` in the diff to make sure that no logic was changed.
What has changed?
You can run the formatter on the whole project by running `npm run format` and ex/include files from the formatter, and enter your custom clang-format config in a formatconfig.json see webmat readme for more
> Automatic format!
